@echo off
cd /d "%~dp0"
if not exist venv (
    echo Creating Python virtual environment...
    python -m venv venv
)
echo Activating venv...
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Forecast Service...
uvicorn app:app --host 127.0.0.1 --port 8000 --reload
