<?php
require_once __DIR__ . '/../../includes/db.php';
$types = [];
if (is_file(__DIR__ . '/../../includes/vehicle_types.php')) { require_once __DIR__ . '/../../includes/vehicle_types.php'; $types = vehicle_types(); }
$db = db();
$plate = trim($_GET['plate'] ?? '');
$stmt = $db->prepare("SELECT plate_number, vehicle_type, operator_name, coop_name, franchise_id, route_id, status, created_at FROM vehicles WHERE plate_number=?");
$stmt->bind_param('s', $plate);
$stmt->execute();
$v = $stmt->get_result()->fetch_assoc();
header('Content-Type: text/html; charset=utf-8');
if (!$v) { echo '<div class="text-sm">Vehicle not found.</div>'; exit; }
echo '<div class="space-y-6">';
$statClass = 'bg-green-100 text-green-700';
if ($v['status'] === 'Suspended') $statClass = 'bg-yellow-100 text-yellow-700';
if ($v['status'] === 'Deactivated') $statClass = 'bg-red-100 text-red-700';
echo '<div class="flex items-center justify-between"><div class="flex items-center gap-2"><span class="px-2 py-1 rounded bg-accent/10 text-accent">PUV</span><h2 class="text-lg font-semibold">'.htmlspecialchars($v['plate_number']).'</h2></div><span class="px-2 py-1 rounded '.$statClass.'">'.htmlspecialchars($v['status']).'</span></div>';
echo '<div class="grid grid-cols-1 gap-6">';
echo '<div class="p-4 border rounded ring-1 ring-accent/20 dark:border-slate-700 bg-white dark:bg-slate-900"><div class="text-sm space-y-1"><div><span class="font-semibold">Type:</span> '.htmlspecialchars($v['vehicle_type']).'</div><div><span class="font-semibold">Operator:</span> '.htmlspecialchars($v['operator_name']).'</div><div><span class="font-semibold">COOP:</span> '.htmlspecialchars($v['coop_name'] ?? '').'</div><div><span class="font-semibold">Franchise ID:</span> '.htmlspecialchars($v['franchise_id'] ?? '').'</div><div><span class="font-semibold">Route ID:</span> '.htmlspecialchars($v['route_id'] ?? '').'</div><div><span class="font-semibold">Created:</span> '.htmlspecialchars($v['created_at']).'</div></div></div>';
echo '<div class="p-4 border rounded ring-1 ring-secondary/20 dark:border-slate-700 bg-white dark:bg-slate-900"><h3 class="text-md font-semibold mb-3">Status & Type</h3><div class="grid grid-cols-1 gap-3"><form id="formStatus" class="flex items-center gap-2" method="POST" action="/tmm/admin/api/module1/update_vehicle.php"><input type="hidden" name="plate_number" value="'.htmlspecialchars($v['plate_number']).'"><select name="status" class="px-2 py-2 border rounded bg-slate-50 dark:bg-slate-800 dark:border-slate-700 w-full"><option>Status</option><option '.($v['status']==='Active'?'selected':'').'>Active</option><option '.($v['status']==='Suspended'?'selected':'').'>Suspended</option><option '.($v['status']==='Deactivated'?'selected':'').'>Deactivated</option></select><button class="px-3 py-2 rounded bg-[#4CAF50] text-white shrink-0">Save</button></form><form id="formType" class="flex items-center gap-2" method="POST" action="/tmm/admin/api/module1/update_vehicle.php"><input type="hidden" name="plate_number" value="'.htmlspecialchars($v['plate_number']).'"><select name="vehicle_type" class="px-2 py-2 border rounded bg-slate-50 dark:bg-slate-800 dark:border-slate-700 w-full"><option>Select vehicle type</option>';
foreach ($types as $t) { echo '<option '.($v['vehicle_type']===$t?'selected':'').'>'.htmlspecialchars($t).'</option>'; }
echo '</select><button class="px-3 py-2 rounded bg-[#4CAF50] text-white shrink-0">Save</button></form></div></div>';
echo '<div class="p-4 border rounded ring-1 ring-secondary/20 dark:border-slate-700 bg-white dark:bg-slate-900"><h3 class="text-md font-semibold mb-2">Documents</h3><div class="text-sm space-y-2">';
$stmtD = $db->prepare("SELECT type, file_path, uploaded_at FROM documents WHERE plate_number=? ORDER BY uploaded_at DESC");
$stmtD->bind_param('s', $plate);
$stmtD->execute();
$resD = $stmtD->get_result();
if ($resD->num_rows === 0) { echo '<div>No documents uploaded.</div>'; }
while ($d = $resD->fetch_assoc()) {
  echo '<div><span class="font-semibold">'.htmlspecialchars($d['type']).':</span> <a class="underline" href="/tmm/admin/'.htmlspecialchars($d['file_path']).'" target="_blank">View</a> <span class="text-xs">('.htmlspecialchars($d['uploaded_at']).')</span></div>';
}
echo '</div><div class="mt-4"><h4 class="text-sm font-semibold mb-2">Upload Documents</h4><form id="formUpload" class="grid grid-cols-1 md:grid-cols-4 gap-2" method="POST" action="/tmm/admin/api/module1/upload_docs.php"><input type="hidden" name="plate_number" value="'.htmlspecialchars($v['plate_number']).'"><div><label class="text-xs block mb-1">OR</label><input name="or" type="file" class="w-full text-sm"></div><div><label class="text-xs block mb-1">CR</label><input name="cr" type="file" class="w-full text-sm"></div><div><label class="text-xs block mb-1">Deed</label><input name="deed" type="file" class="w-full text-sm"></div><div class="flex items-end"><button class="px-3 py-2 rounded bg-[#4CAF50] text-white w-full">Upload</button></div></form><div id="uploadProgress" class="w-full bg-slate-200 dark:bg-slate-700 h-2 rounded mt-2 overflow-hidden hidden"><div id="uploadBar" class="h-2 bg-[#4CAF50] w-0"></div></div><div id="uploadMsg" class="text-xs mt-2"></div></div></div>';
echo '</div>';
$stmtA = $db->prepare("SELECT route_id, terminal_name, status, assigned_at FROM terminal_assignments WHERE plate_number=?");
$stmtA->bind_param('s', $plate);
$stmtA->execute();
$a = $stmtA->get_result()->fetch_assoc();
echo '<div class="grid grid-cols-1 gap-6">';
echo '<div class="p-4 border rounded ring-1 ring-accent/20 dark:border-slate-700 bg-white dark:bg-slate-900"><h3 class="text-md font-semibold mb-2">Terminal Assignment</h3><div class="text-sm">';
if (!$a) { echo 'No assignment yet.'; } else { echo 'Route: '.htmlspecialchars($a['route_id']).' • Terminal: '.htmlspecialchars($a['terminal_name']).' • Status: '.htmlspecialchars($a['status']).' • Assigned: '.htmlspecialchars($a['assigned_at']); }
echo '</div><form id="formAssign" class="mt-3 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-2" method="POST" action="/tmm/admin/api/module1/assign_route.php"><input type="hidden" name="plate_number" value="'.htmlspecialchars($v['plate_number']).'"><input name="route_id" class="px-2 py-2 border rounded bg-slate-50 dark:bg-slate-800 dark:border-slate-700 w-full" placeholder="Route ID" value="'.htmlspecialchars($a['route_id'] ?? '').'"><input name="terminal_name" class="px-2 py-2 border rounded bg-slate-50 dark:bg-slate-800 dark:border-slate-700 w-full" placeholder="Terminal" value="'.htmlspecialchars($a['terminal_name'] ?? '').'"><select name="status" class="px-2 py-2 border rounded bg-slate-50 dark:bg-slate-800 dark:border-slate-700 w-full"><option '.(($a['status'] ?? '')==='Authorized'?'selected':'').'>Authorized</option><option '.(($a['status'] ?? '')!=='Authorized'?'selected':'').'>Pending</option></select><div class="sm:col-span-2 md:col-span-1"><button class="px-3 py-2 rounded bg-[#4CAF50] text-white w-full">Save</button></div></form>';
echo '<div class="p-4 border rounded ring-1 ring-secondary/20 dark:border-slate-700 bg-white dark:bg-slate-900"><h3 class="text-md font-semibold mb-2">Link Operator/Coop</h3><form id="formLink" class="grid grid-cols-1 md:grid-cols-3 gap-2" method="POST" action="/tmm/admin/api/module1/link_vehicle_operator.php"><input type="hidden" name="plate_number" value="'.htmlspecialchars($v['plate_number']).'"><input name="operator_name" class="px-2 py-2 border rounded bg-slate-50 dark:bg-slate-800 dark:border-slate-700 w-full" placeholder="Operator name" value="'.htmlspecialchars($v['operator_name'] ?? '').'"><input name="coop_name" class="px-2 py-2 border rounded bg-slate-50 dark:bg-slate-800 dark:border-slate-700 w-full" placeholder="Cooperative" value="'.htmlspecialchars($v['coop_name'] ?? '').'"><button class="px-3 py-2 rounded bg-[#4CAF50] text-white">Link</button></form></div>';
echo '</div>';
echo '<script>(function(){function refresh(){fetch(\"/tmm/admin/api/module1/view_html.php?plate='.htmlspecialchars($v['plate_number']).'\").then(function(r){return r.text()}).then(function(html){var c=document.getElementById(\"vehicleModalBody\"); if(c){c.innerHTML=html; if(window.lucide&&window.lucide.createIcons) window.lucide.createIcons();}})} function bind(id){var f=document.getElementById(id); if(!f) return; f.addEventListener(\"submit\", function(e){e.preventDefault(); var fd=new FormData(f); fetch(f.action, {method:\"POST\", body:fd}).then(function(){refresh()})})} bind(\"formStatus\"); bind(\"formType\"); bind(\"formAssign\"); bind(\"formLink\"); var fu=document.getElementById(\"formUpload\"); if(fu){fu.addEventListener(\"submit\", function(e){e.preventDefault(); var fd=new FormData(fu); var xhr=new XMLHttpRequest(); var bar=document.getElementById(\"uploadBar\"), wrap=document.getElementById(\"uploadProgress\"), msg=document.getElementById(\"uploadMsg\"); wrap.classList.remove(\"hidden\"); bar.style.width=\"0%\"; msg.textContent=\"\"; xhr.upload.addEventListener(\"progress\", function(ev){ if(ev.lengthComputable){ var p=Math.round((ev.loaded/ev.total)*100); bar.style.width=p+\"%\"; } }); xhr.onreadystatechange=function(){ if(xhr.readyState===4){ if(xhr.status>=200 && xhr.status<300){ msg.textContent=\"Uploaded\"; refresh(); } else { msg.textContent=\"Upload failed\"; } setTimeout(function(){ wrap.classList.add(\"hidden\"); bar.style.width=\"0%\"; }, 800); } }; xhr.open(\"POST\", fu.action); xhr.send(fd); }); } })()</script>';
?> 
